// GENERATED by tools/generate-city-activity.js — do not edit by hand.
// Per-city calendar summary; js/city-config.js reads it to delist cities
// with nothing upcoming (see isCityActive there).
window.CITY_ACTIVITY = {
 "generatedAt": "2026-09-19",
 "cities": {
  "nyc": {
   "dates": [
    "2026-09-19",
    "2026-09-20",
    "2026-09-24",
    "2026-09-25",
    "2026-09-26",
    "2026-10-01",
    "2026-10-03",
    "2026-10-08",
    "2026-10-15",
    "2026-10-16",
    "2026-10-22",
    "2026-10-23",
    "2026-10-29",
    "2026-10-31",
    "2026-11-05",
    "2026-11-07",
    "2026-11-12",
    "2026-11-19",
    "2026-11-20",
    "2026-11-26",
    "2026-11-27",
    "2026-11-28",
    "2026-12-03",
    "2026-12-05",
    "2026-12-10"
   ],
   "recurring": 6,
   "festivalUntil": "2026-09-20"
  },
  "seattle": {
   "dates": [
    "2026-11-07"
   ],
   "recurring": 2,
   "festivalUntil": null
  },
  "la": {
   "dates": [
    "2026-09-19",
    "2026-09-20",
    "2026-10-01",
    "2026-10-02",
    "2026-10-16",
    "2026-10-17",
    "2026-10-31",
    "2026-11-05",
    "2026-11-06",
    "2026-11-29",
    "2026-12-03",
    "2026-12-04",
    "2026-12-11",
    "2027-01-01"
   ],
   "recurring": 2,
   "festivalUntil": null
  },
  "toronto": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "london": {
   "dates": [
    "2026-09-19",
    "2026-09-26",
    "2026-10-17",
    "2026-11-21",
    "2026-12-31",
    "2027-08-29"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "chicago": {
   "dates": [
    "2026-09-19",
    "2026-10-10"
   ],
   "recurring": 2,
   "festivalUntil": null
  },
  "berlin": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "palm-springs": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": "2027-02-22"
  },
  "denver": {
   "dates": [
    "2026-10-03"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "dallas": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": "2027-03-28"
  },
  "dc": {
   "dates": [
    "2026-09-26"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "vegas": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "atlanta": {
   "dates": [
    "2026-11-14"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "nola": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "sf": {
   "dates": [
    "2026-09-19",
    "2026-09-25",
    "2026-09-26",
    "2026-10-17"
   ],
   "recurring": 1,
   "festivalUntil": "2026-09-27"
  },
  "portland": {
   "dates": [
    "2026-09-19",
    "2026-10-10",
    "2026-12-31"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "sitges": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "boston": {
   "dates": [
    "2026-09-19",
    "2026-09-20",
    "2026-09-26",
    "2026-10-09",
    "2026-10-10",
    "2026-10-15",
    "2026-10-18",
    "2026-10-24",
    "2026-10-25",
    "2026-11-15",
    "2026-11-19",
    "2026-11-28",
    "2026-11-29",
    "2026-12-17",
    "2026-12-20",
    "2026-12-26"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "phoenix": {
   "dates": [
    "2026-10-10"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "ptown": {
   "dates": [
    "2026-10-30"
   ],
   "recurring": 0,
   "festivalUntil": "2026-11-01"
  },
  "san-diego": {
   "dates": [
    "2026-10-16"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "philly": {
   "dates": [
    "2026-10-30"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "miami": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "pv": {
   "dates": [
    "2027-01-23",
    "2027-01-24",
    "2027-01-25",
    "2027-01-26",
    "2027-01-27",
    "2027-01-28",
    "2027-01-29",
    "2027-01-30",
    "2027-01-31"
   ],
   "recurring": 0,
   "festivalUntil": "2027-01-31"
  },
  "austin": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "houston": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "sacramento": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "poconos": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "asbury-park": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "torremolinos": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "fort-lauderdale": {
   "dates": [
    "2026-09-19",
    "2026-09-25",
    "2026-09-26",
    "2026-10-02",
    "2026-10-03",
    "2026-10-09",
    "2026-10-10",
    "2026-10-16",
    "2026-10-17",
    "2026-10-23",
    "2026-10-24",
    "2026-10-30",
    "2026-11-01",
    "2026-11-06",
    "2026-11-07"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "montreal": {
   "dates": [
    "2026-09-19",
    "2026-10-03"
   ],
   "recurring": 0,
   "festivalUntil": "2027-04-11"
  },
  "fire-island": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "vancouver": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "bangkok": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "paris": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "manchester": {
   "dates": [
    "2026-09-20",
    "2026-09-27",
    "2026-10-02",
    "2026-10-10",
    "2026-11-14",
    "2026-12-12"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "brighton": {
   "dates": [
    "2026-12-05"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "birmingham": {
   "dates": [
    "2026-09-26"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "dublin": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "mexico-city": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "madrid": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": "2026-12-09"
  },
  "amsterdam": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "sao-paulo": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "bogota": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "honolulu": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "hong-kong": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "tokyo": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  }
 }
};
