// GENERATED by tools/generate-city-activity.js — do not edit by hand.
// Per-city calendar summary; js/city-config.js reads it to delist cities
// with nothing upcoming (see isCityActive there).
window.CITY_ACTIVITY = {
 "generatedAt": "2026-09-04",
 "cities": {
  "nyc": {
   "dates": [
    "2026-09-05",
    "2026-09-17",
    "2026-09-18",
    "2026-09-19",
    "2026-09-20"
   ],
   "recurring": 6,
   "festivalUntil": "2026-09-20"
  },
  "seattle": {
   "dates": [
    "2026-09-12"
   ],
   "recurring": 2,
   "festivalUntil": null
  },
  "la": {
   "dates": [
    "2026-09-04",
    "2026-09-11",
    "2026-09-12",
    "2026-09-18",
    "2026-09-19",
    "2026-09-20",
    "2026-10-16",
    "2026-10-17",
    "2026-10-31"
   ],
   "recurring": 3,
   "festivalUntil": null
  },
  "toronto": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "london": {
   "dates": [
    "2026-09-19",
    "2026-10-17",
    "2026-11-21",
    "2026-12-31"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "chicago": {
   "dates": [
    "2026-09-19"
   ],
   "recurring": 2,
   "festivalUntil": null
  },
  "berlin": {
   "dates": [
    "2026-09-09",
    "2026-09-10",
    "2026-09-11",
    "2026-09-12",
    "2026-09-13"
   ],
   "recurring": 0,
   "festivalUntil": "2026-09-13"
  },
  "palm-springs": {
   "dates": [
    "2026-09-11"
   ],
   "recurring": 0,
   "festivalUntil": "2027-02-22"
  },
  "denver": {
   "dates": [
    "2026-10-03"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "dallas": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": "2027-03-28"
  },
  "dc": {
   "dates": [
    "2026-09-26"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "vegas": {
   "dates": [
    "2026-09-05"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "atlanta": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "nola": {
   "dates": [
    "2026-09-04",
    "2026-09-05",
    "2026-09-06"
   ],
   "recurring": 0,
   "festivalUntil": "2026-09-07"
  },
  "sf": {
   "dates": [
    "2026-09-25",
    "2026-09-26"
   ],
   "recurring": 1,
   "festivalUntil": "2026-09-27"
  },
  "portland": {
   "dates": [
    "2026-09-19",
    "2026-12-31"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "sitges": {
   "dates": [
    "2026-09-04",
    "2026-09-05",
    "2026-09-06",
    "2026-09-07",
    "2026-09-08",
    "2026-09-09",
    "2026-09-10",
    "2026-09-11",
    "2026-09-12",
    "2026-09-13",
    "2026-09-14"
   ],
   "recurring": 0,
   "festivalUntil": "2026-09-13"
  },
  "boston": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "phoenix": {
   "dates": [
    "2026-10-10"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "ptown": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": "2026-11-01"
  },
  "san-diego": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "philly": {
   "dates": [],
   "recurring": 0,
   "festivalUntil": null
  },
  "brighton": {
   "dates": [
    "2026-12-05"
   ],
   "recurring": 0,
   "festivalUntil": null
  },
  "birmingham": {
   "dates": [
    "2026-09-26"
   ],
   "recurring": 0,
   "festivalUntil": null
  }
 }
};
