// Bear Event Scraper City Configuration
// This file is generated by tools/generate-scraper-cities.js from js/city-config.js.
// Do not edit this file directly.
//
// USAGE RESTRICTIONS:
// - This is a pure JavaScript configuration file
// - Must export a default cities configuration object
// - Can be imported in both Scriptable and web environments
// - Keep this file environment-agnostic (no Scriptable or DOM APIs)
const scraperCities = {
  "nyc": {
    "calendar": "chunky-dad-nyc",
    "timezone": "America/New_York",
    "patterns": [
      "new york",
      "nyc",
      "manhattan",
      "brooklyn",
      "queens",
      "bronx"
    ],
    "coordinates": {
      "lat": 40.7831,
      "lng": -73.9712
    }
  },
  "seattle": {
    "calendar": "chunky-dad-seattle",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "seattle"
    ],
    "coordinates": {
      "lat": 47.6062,
      "lng": -122.3321
    }
  },
  "la": {
    "calendar": "chunky-dad-la",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "los angeles",
      "hollywood",
      "west hollywood",
      "weho",
      "dtla",
      "downtown los angeles",
      "downtown la",
      "downtown l.a.",
      "long beach",
      "santa monica",
      "d>u>r>o"
    ],
    "coordinates": {
      "lat": 34.0522,
      "lng": -118.2437
    }
  },
  "toronto": {
    "calendar": "chunky-dad-toronto",
    "timezone": "America/Toronto",
    "patterns": [
      "toronto"
    ],
    "coordinates": {
      "lat": 43.6532,
      "lng": -79.3832
    }
  },
  "london": {
    "calendar": "chunky-dad-london",
    "timezone": "Europe/London",
    "patterns": [
      "london"
    ],
    "coordinates": {
      "lat": 51.5074,
      "lng": -0.1278
    }
  },
  "chicago": {
    "calendar": "chunky-dad-chicago",
    "timezone": "America/Chicago",
    "patterns": [
      "chicago",
      "chi"
    ],
    "coordinates": {
      "lat": 41.8781,
      "lng": -87.6298
    }
  },
  "berlin": {
    "calendar": "chunky-dad-berlin",
    "timezone": "Europe/Berlin",
    "patterns": [
      "berlin"
    ],
    "coordinates": {
      "lat": 52.52,
      "lng": 13.405
    }
  },
  "palm-springs": {
    "calendar": "chunky-dad-palm-springs",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "palm springs",
      "cathedral city",
      "palm desert",
      "rancho mirage",
      "indian wells",
      "la quinta",
      "desert hot springs",
      "greater palm springs"
    ],
    "coordinates": {
      "lat": 33.8303,
      "lng": -116.5453
    }
  },
  "denver": {
    "calendar": "chunky-dad-denver",
    "timezone": "America/Denver",
    "patterns": [
      "denver"
    ],
    "coordinates": {
      "lat": 39.7392,
      "lng": -104.9903
    }
  },
  "dallas": {
    "calendar": "chunky-dad-dallas",
    "timezone": "America/Chicago",
    "patterns": [
      "dallas"
    ],
    "coordinates": {
      "lat": 32.7767,
      "lng": -96.797
    }
  },
  "dc": {
    "calendar": "chunky-dad-dc",
    "timezone": "America/New_York",
    "patterns": [
      "dc",
      "washington, dc",
      "washington dc",
      "district of columbia"
    ],
    "coordinates": {
      "lat": 38.9072,
      "lng": -77.0369
    }
  },
  "vegas": {
    "calendar": "chunky-dad-vegas",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "las vegas",
      "vegas"
    ],
    "coordinates": {
      "lat": 36.1699,
      "lng": -115.1398
    }
  },
  "atlanta": {
    "calendar": "chunky-dad-atlanta",
    "timezone": "America/New_York",
    "patterns": [
      "atlanta",
      "atl"
    ],
    "coordinates": {
      "lat": 33.749,
      "lng": -84.388
    }
  },
  "nola": {
    "calendar": "chunky-dad-new-orleans",
    "timezone": "America/Chicago",
    "patterns": [
      "new orleans"
    ],
    "coordinates": {
      "lat": 29.9511,
      "lng": -90.0715
    }
  },
  "sf": {
    "calendar": "chunky-dad-sf",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "san francisco",
      "san fransisco",
      "sf",
      "castro",
      "san jose",
      "oakland"
    ],
    "coordinates": {
      "lat": 37.7749,
      "lng": -122.4194
    }
  },
  "portland": {
    "calendar": "chunky-dad-portland",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "portland"
    ],
    "coordinates": {
      "lat": 45.5152,
      "lng": -122.6784
    }
  },
  "sitges": {
    "calendar": "chunky-dad-sitges",
    "timezone": "Europe/Madrid",
    "patterns": [
      "sitges"
    ],
    "coordinates": {
      "lat": 41.2379,
      "lng": 1.8057
    }
  },
  "boston": {
    "calendar": "chunky-dad-boston",
    "timezone": "America/New_York",
    "patterns": [
      "boston",
      "boton",
      "bostom",
      "bostun",
      "bostan"
    ],
    "coordinates": {
      "lat": 42.3601,
      "lng": -71.0589
    }
  },
  "phoenix": {
    "calendar": "chunky-dad-phoenix",
    "timezone": "America/Phoenix",
    "patterns": [
      "phoenix"
    ],
    "coordinates": {
      "lat": 33.4484,
      "lng": -112.074
    }
  },
  "ptown": {
    "calendar": "chunky-dad-provincetown",
    "timezone": "America/New_York",
    "patterns": [
      "provincetown",
      "ptown"
    ],
    "coordinates": {
      "lat": 42.0526,
      "lng": -70.1865
    }
  },
  "san-diego": {
    "calendar": "chunky-dad-san-diego",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "san diego"
    ],
    "coordinates": {
      "lat": 32.7157,
      "lng": -117.1611
    }
  },
  "philly": {
    "calendar": "chunky-dad-philadelphia",
    "timezone": "America/New_York",
    "patterns": [
      "philadelphia",
      "philly"
    ],
    "coordinates": {
      "lat": 39.9526,
      "lng": -75.1652
    }
  },
  "miami": {
    "calendar": "chunky-dad-miami",
    "timezone": "America/New_York",
    "patterns": [
      "miami",
      "south beach",
      "miami beach",
      "key west"
    ],
    "coordinates": {
      "lat": 25.7617,
      "lng": -80.1918
    }
  },
  "pv": {
    "calendar": "chunky-dad-pv",
    "timezone": "America/Mexico_City",
    "patterns": [
      "puerto vallarta",
      "vallarta",
      "pv",
      "p.v"
    ],
    "coordinates": {
      "lat": 20.6534,
      "lng": -105.2253
    }
  },
  "austin": {
    "calendar": "chunky-dad-austin",
    "timezone": "America/Chicago",
    "patterns": [
      "austin"
    ],
    "coordinates": {
      "lat": 30.2672,
      "lng": -97.7431
    }
  },
  "houston": {
    "calendar": "chunky-dad-houston",
    "timezone": "America/Chicago",
    "patterns": [
      "houston"
    ],
    "coordinates": {
      "lat": 29.7604,
      "lng": -95.3698
    }
  },
  "sacramento": {
    "calendar": "chunky-dad-sacramento",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "sacramento"
    ],
    "coordinates": {
      "lat": 38.5816,
      "lng": -121.4944
    }
  },
  "poconos": {
    "calendar": "chunky-dad-poconos",
    "timezone": "America/New_York",
    "patterns": [
      "poconos",
      "pocono",
      "east stroudsburg"
    ],
    "coordinates": {
      "lat": 41.0339,
      "lng": -75.3188
    }
  },
  "asbury-park": {
    "calendar": "chunky-dad-asbury-park",
    "timezone": "America/New_York",
    "patterns": [
      "asbury park",
      "asbury"
    ],
    "coordinates": {
      "lat": 40.2204,
      "lng": -74.0121
    }
  },
  "torremolinos": {
    "calendar": "chunky-dad-torremolinos",
    "timezone": "Europe/Madrid",
    "patterns": [
      "torremolinos"
    ],
    "coordinates": {
      "lat": 36.6213,
      "lng": -4.4998
    }
  },
  "fort-lauderdale": {
    "calendar": "chunky-dad-fort-lauderdale",
    "timezone": "America/New_York",
    "patterns": [
      "fort lauderdale",
      "fll",
      "ft lauderdale",
      "wilton manors"
    ],
    "coordinates": {
      "lat": 26.1224,
      "lng": -80.1373
    }
  },
  "montreal": {
    "calendar": "chunky-dad-montreal",
    "timezone": "America/Toronto",
    "patterns": [
      "montreal",
      "mtl"
    ],
    "coordinates": {
      "lat": 45.5019,
      "lng": -73.5674
    }
  },
  "fire-island": {
    "calendar": "chunky-dad-fire-island",
    "timezone": "America/New_York",
    "patterns": [
      "fire island",
      "cherry grove",
      "fire island pines"
    ],
    "coordinates": {
      "lat": 40.6482,
      "lng": -73.085
    }
  },
  "vancouver": {
    "calendar": "chunky-dad-vancouver",
    "timezone": "America/Vancouver",
    "patterns": [
      "vancouver",
      "yvr"
    ],
    "coordinates": {
      "lat": 49.2827,
      "lng": -123.1207
    }
  },
  "bangkok": {
    "calendar": "chunky-dad-bangkok",
    "timezone": "Asia/Bangkok",
    "patterns": [
      "bangkok",
      "bkk"
    ],
    "coordinates": {
      "lat": 13.7563,
      "lng": 100.5018
    }
  },
  "paris": {
    "calendar": "chunky-dad-paris",
    "timezone": "Europe/Paris",
    "patterns": [
      "paris"
    ],
    "coordinates": {
      "lat": 48.8566,
      "lng": 2.3522
    }
  },
  "manchester": {
    "calendar": "chunky-dad-manchester",
    "timezone": "Europe/London",
    "patterns": [
      "manchester",
      "mcr"
    ],
    "coordinates": {
      "lat": 53.4808,
      "lng": -2.2426
    }
  },
  "brighton": {
    "calendar": "chunky-dad-brighton",
    "timezone": "Europe/London",
    "patterns": [
      "brighton",
      "brighton and hove"
    ],
    "coordinates": {
      "lat": 50.8225,
      "lng": -0.1372
    }
  },
  "birmingham": {
    "calendar": "chunky-dad-birmingham",
    "timezone": "Europe/London",
    "patterns": [
      "birmingham"
    ],
    "coordinates": {
      "lat": 52.4862,
      "lng": -1.8904
    }
  },
  "dublin": {
    "calendar": "chunky-dad-dublin",
    "timezone": "Europe/Dublin",
    "patterns": [
      "dublin"
    ],
    "coordinates": {
      "lat": 53.3498,
      "lng": -6.2603
    }
  },
  "mexico-city": {
    "calendar": "chunky-dad-mexico-city",
    "timezone": "America/Mexico_City",
    "patterns": [
      "mexico city",
      "cdmx"
    ],
    "coordinates": {
      "lat": 19.4326,
      "lng": -99.1332
    }
  },
  "madrid": {
    "calendar": "chunky-dad-madrid",
    "timezone": "Europe/Madrid",
    "patterns": [
      "madrid"
    ],
    "coordinates": {
      "lat": 40.4168,
      "lng": -3.7038
    }
  },
  "amsterdam": {
    "calendar": "chunky-dad-amsterdam",
    "timezone": "Europe/Amsterdam",
    "patterns": [
      "amsterdam"
    ],
    "coordinates": {
      "lat": 52.3676,
      "lng": 4.9041
    }
  },
  "sao-paulo": {
    "calendar": "chunky-dad-sao-paulo",
    "timezone": "America/Sao_Paulo",
    "patterns": [
      "sao paulo",
      "são paulo"
    ],
    "coordinates": {
      "lat": -23.5505,
      "lng": -46.6333
    }
  },
  "bogota": {
    "calendar": "chunky-dad-bogota",
    "timezone": "America/Bogota",
    "patterns": [
      "bogota",
      "bogotá"
    ],
    "coordinates": {
      "lat": 4.711,
      "lng": -74.0721
    }
  },
  "honolulu": {
    "calendar": "chunky-dad-honolulu",
    "timezone": "Pacific/Honolulu",
    "patterns": [
      "honolulu",
      "hawaii",
      "oahu",
      "waikiki"
    ],
    "coordinates": {
      "lat": 21.3069,
      "lng": -157.8583
    }
  },
  "hong-kong": {
    "calendar": "chunky-dad-hong-kong",
    "timezone": "Asia/Hong_Kong",
    "patterns": [
      "hong kong",
      "hk"
    ],
    "coordinates": {
      "lat": 22.3193,
      "lng": 114.1694
    }
  },
  "tokyo": {
    "calendar": "chunky-dad-tokyo",
    "timezone": "Asia/Tokyo",
    "patterns": [
      "tokyo"
    ],
    "coordinates": {
      "lat": 35.6762,
      "lng": 139.6503
    }
  },
  "sydney": {
    "calendar": "chunky-dad-sydney",
    "timezone": "Australia/Sydney",
    "patterns": [
      "sydney"
    ],
    "coordinates": {
      "lat": -33.8688,
      "lng": 151.2093
    }
  },
  "melbourne": {
    "calendar": "chunky-dad-melbourne",
    "timezone": "Australia/Melbourne",
    "patterns": [
      "melbourne"
    ],
    "coordinates": {
      "lat": -37.8136,
      "lng": 144.9631
    }
  },
  "brisbane": {
    "calendar": "chunky-dad-brisbane",
    "timezone": "Australia/Brisbane",
    "patterns": [
      "brisbane",
      "fortitude valley"
    ],
    "coordinates": {
      "lat": -27.4698,
      "lng": 153.0251
    }
  },
  "oslo": {
    "calendar": "chunky-dad-oslo",
    "timezone": "Europe/Oslo",
    "patterns": [
      "oslo"
    ],
    "coordinates": {
      "lat": 59.9139,
      "lng": 10.7522
    }
  },
  "ottawa": {
    "calendar": "chunky-dad-ottawa",
    "timezone": "America/Toronto",
    "patterns": [
      "ottawa"
    ],
    "coordinates": {
      "lat": 45.4215,
      "lng": -75.6972
    }
  },
  "salt-lake-city": {
    "calendar": "chunky-dad-salt-lake-city",
    "timezone": "America/Denver",
    "patterns": [
      "salt lake city",
      "salt lake",
      "slc"
    ],
    "coordinates": {
      "lat": 40.7608,
      "lng": -111.891
    }
  },
  "orlando": {
    "calendar": "chunky-dad-orlando",
    "timezone": "America/New_York",
    "patterns": [
      "orlando",
      "lake buena vista"
    ],
    "coordinates": {
      "lat": 28.5383,
      "lng": -81.3792
    }
  },
  "edinburgh": {
    "calendar": "chunky-dad-edinburgh",
    "timezone": "Europe/London",
    "patterns": [
      "edinburgh"
    ],
    "coordinates": {
      "lat": 55.9533,
      "lng": -3.1883
    }
  },
  "prague": {
    "calendar": "chunky-dad-prague",
    "timezone": "Europe/Prague",
    "patterns": [
      "prague",
      "praha"
    ],
    "coordinates": {
      "lat": 50.0755,
      "lng": 14.4378
    }
  },
  "leipzig": {
    "calendar": "chunky-dad-leipzig",
    "timezone": "Europe/Berlin",
    "patterns": [
      "leipzig"
    ],
    "coordinates": {
      "lat": 51.3397,
      "lng": 12.3731
    }
  },
  "cologne": {
    "calendar": "chunky-dad-cologne",
    "timezone": "Europe/Berlin",
    "patterns": [
      "cologne",
      "köln",
      "koeln"
    ],
    "coordinates": {
      "lat": 50.9375,
      "lng": 6.9603
    }
  },
  "brussels": {
    "calendar": "chunky-dad-brussels",
    "timezone": "Europe/Brussels",
    "patterns": [
      "brussels",
      "bruxelles",
      "brussel"
    ],
    "coordinates": {
      "lat": 50.8503,
      "lng": 4.3517
    }
  },
  "seoul": {
    "calendar": "chunky-dad-seoul",
    "timezone": "Asia/Seoul",
    "patterns": [
      "seoul"
    ],
    "coordinates": {
      "lat": 37.5665,
      "lng": 126.978
    }
  },
  "singapore": {
    "calendar": "chunky-dad-singapore",
    "timezone": "Asia/Singapore",
    "patterns": [
      "singapore"
    ],
    "coordinates": {
      "lat": 1.3521,
      "lng": 103.8198
    }
  },
  "taipei": {
    "calendar": "chunky-dad-taipei",
    "timezone": "Asia/Taipei",
    "patterns": [
      "taipei"
    ],
    "coordinates": {
      "lat": 25.033,
      "lng": 121.5654
    }
  },
  "gran-canaria": {
    "calendar": "chunky-dad-gran-canaria",
    "timezone": "Atlantic/Canary",
    "patterns": [
      "gran canaria",
      "maspalomas",
      "playa del ingles",
      "playa del inglés"
    ],
    "coordinates": {
      "lat": 27.7606,
      "lng": -15.586
    }
  },
  "indianapolis": {
    "calendar": "chunky-dad-indianapolis",
    "timezone": "America/Indiana/Indianapolis",
    "patterns": [
      "indianapolis"
    ],
    "coordinates": {
      "lat": 39.7684,
      "lng": -86.1581
    }
  },
  "gettysburg": {
    "calendar": "chunky-dad-gettysburg",
    "timezone": "America/New_York",
    "patterns": [
      "gettysburg"
    ],
    "coordinates": {
      "lat": 39.8309,
      "lng": -77.2311
    }
  }
};

// Export for different environments
// Scriptable environment
if (typeof module !== 'undefined' && module.exports) {
  module.exports = scraperCities;
}

// ES6 module environment
if (typeof window === 'undefined' && typeof importModule !== 'undefined') {
  // Scriptable environment - make available for importModule
  scraperCities;
} else if (typeof window !== 'undefined') {
  // Browser environment - attach to window
  window.scraperCities = scraperCities;
}

// Default export for ES6 modules
scraperCities;
