// Bear Event Scraper City Configuration
// This file is generated by tools/generate-scraper-cities.js from js/city-config.js.
// Do not edit this file directly.
//
// USAGE RESTRICTIONS:
// - This is a pure JavaScript configuration file
// - Must export a default cities configuration object
// - Can be imported in both Scriptable and web environments
// - Keep this file environment-agnostic (no Scriptable or DOM APIs)
const scraperCities = {
  "nyc": {
    "calendar": "chunky-dad-nyc",
    "timezone": "America/New_York",
    "patterns": [
      "new york",
      "nyc",
      "manhattan",
      "brooklyn",
      "queens",
      "bronx"
    ]
  },
  "seattle": {
    "calendar": "chunky-dad-seattle",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "seattle"
    ]
  },
  "la": {
    "calendar": "chunky-dad-la",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "los angeles",
      "hollywood",
      "west hollywood",
      "weho",
      "dtla",
      "downtown los angeles",
      "long beach",
      "santa monica",
      "d>u>r>o"
    ]
  },
  "toronto": {
    "calendar": "chunky-dad-toronto",
    "timezone": "America/Toronto",
    "patterns": [
      "toronto"
    ]
  },
  "london": {
    "calendar": "chunky-dad-london",
    "timezone": "Europe/London",
    "patterns": [
      "london"
    ]
  },
  "chicago": {
    "calendar": "chunky-dad-chicago",
    "timezone": "America/Chicago",
    "patterns": [
      "chicago",
      "chi"
    ]
  },
  "berlin": {
    "calendar": "chunky-dad-berlin",
    "timezone": "Europe/Berlin",
    "patterns": [
      "berlin"
    ]
  },
  "palm-springs": {
    "calendar": "chunky-dad-palm-springs",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "palm springs"
    ]
  },
  "denver": {
    "calendar": "chunky-dad-denver",
    "timezone": "America/Denver",
    "patterns": [
      "denver"
    ]
  },
  "dallas": {
    "calendar": "chunky-dad-dallas",
    "timezone": "America/Chicago",
    "patterns": [
      "dallas"
    ]
  },
  "dc": {
    "calendar": "chunky-dad-dc",
    "timezone": "America/New_York",
    "patterns": [
      "dc",
      "washington, dc",
      "washington dc",
      "district of columbia"
    ]
  },
  "vegas": {
    "calendar": "chunky-dad-vegas",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "las vegas",
      "vegas"
    ]
  },
  "atlanta": {
    "calendar": "chunky-dad-atlanta",
    "timezone": "America/New_York",
    "patterns": [
      "atlanta",
      "atl"
    ]
  },
  "nola": {
    "calendar": "chunky-dad-new-orleans",
    "timezone": "America/Chicago",
    "patterns": [
      "new orleans"
    ]
  },
  "sf": {
    "calendar": "chunky-dad-sf",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "san francisco",
      "san fransisco",
      "sf",
      "castro",
      "san jose",
      "oakland"
    ]
  },
  "portland": {
    "calendar": "chunky-dad-portland",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "portland"
    ]
  },
  "sitges": {
    "calendar": "chunky-dad-sitges",
    "timezone": "Europe/Madrid",
    "patterns": [
      "sitges"
    ]
  },
  "boston": {
    "calendar": "chunky-dad-boston",
    "timezone": "America/New_York",
    "patterns": [
      "boston",
      "boton",
      "bostom",
      "bostun",
      "bostan"
    ]
  },
  "phoenix": {
    "calendar": "chunky-dad-phoenix",
    "timezone": "America/Phoenix",
    "patterns": [
      "phoenix"
    ]
  },
  "ptown": {
    "calendar": "chunky-dad-provincetown",
    "timezone": "America/New_York",
    "patterns": [
      "provincetown",
      "ptown"
    ]
  },
  "san-diego": {
    "calendar": "chunky-dad-san-diego",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "san diego"
    ]
  },
  "philly": {
    "calendar": "chunky-dad-philadelphia",
    "timezone": "America/New_York",
    "patterns": [
      "philadelphia",
      "philly"
    ]
  },
  "miami": {
    "calendar": "chunky-dad-miami",
    "timezone": "America/New_York",
    "patterns": [
      "miami",
      "south beach",
      "miami beach",
      "key west"
    ]
  },
  "pv": {
    "calendar": "chunky-dad-puerto-vallerta",
    "timezone": "America/Mexico_City",
    "patterns": [
      "puerto vallarta",
      "vallarta"
    ]
  },
  "austin": {
    "calendar": "chunky-dad-austin",
    "timezone": "America/Chicago",
    "patterns": [
      "austin"
    ]
  },
  "houston": {
    "calendar": "chunky-dad-houston",
    "timezone": "America/Chicago",
    "patterns": [
      "houston"
    ]
  },
  "sacramento": {
    "calendar": "chunky-dad-sacramento",
    "timezone": "America/Los_Angeles",
    "patterns": [
      "sacramento"
    ]
  },
  "poconos": {
    "calendar": "chunky-dad-poconos",
    "timezone": "America/New_York",
    "patterns": [
      "poconos",
      "pocono"
    ]
  },
  "torremolinos": {
    "calendar": "chunky-dad-torremolinos",
    "timezone": "Europe/Madrid",
    "patterns": [
      "torremolinos"
    ]
  },
  "fort-lauderdale": {
    "calendar": "chunky-dad-fort-lauderdale",
    "timezone": "America/New_York",
    "patterns": [
      "fort lauderdale",
      "fll",
      "ft lauderdale"
    ]
  },
  "montreal": {
    "calendar": "chunky-dad-montreal",
    "timezone": "America/Toronto",
    "patterns": [
      "montreal"
    ]
  },
  "fire-island": {
    "calendar": "chunky-dad-fire-island",
    "timezone": "America/New_York",
    "patterns": [
      "fire island",
      "cherry grove",
      "fire island pines"
    ]
  },
  "vancouver": {
    "calendar": "chunky-dad-vancouver",
    "timezone": "America/Vancouver",
    "patterns": [
      "vancouver",
      "yvr"
    ]
  },
  "bangkok": {
    "calendar": "chunky-dad-bangkok",
    "timezone": "Asia/Bangkok",
    "patterns": [
      "bangkok",
      "bkk"
    ]
  },
  "paris": {
    "calendar": "chunky-dad-paris",
    "timezone": "Europe/Paris",
    "patterns": [
      "paris"
    ]
  },
  "manchester": {
    "calendar": "chunky-dad-manchester",
    "timezone": "Europe/London",
    "patterns": [
      "manchester",
      "mcr"
    ]
  },
  "dublin": {
    "calendar": "chunky-dad-dublin",
    "timezone": "Europe/Dublin",
    "patterns": [
      "dublin"
    ]
  },
  "mexico-city": {
    "calendar": "chunky-dad-mexico-city",
    "timezone": "America/Mexico_City",
    "patterns": [
      "mexico city",
      "cdmx"
    ]
  },
  "madrid": {
    "calendar": "chunky-dad-madrid",
    "timezone": "Europe/Madrid",
    "patterns": [
      "madrid"
    ]
  },
  "amsterdam": {
    "calendar": "chunky-dad-amsterdam",
    "timezone": "Europe/Amsterdam",
    "patterns": [
      "amsterdam"
    ]
  },
  "sao-paulo": {
    "calendar": "chunky-dad-sao-paulo",
    "timezone": "America/Sao_Paulo",
    "patterns": [
      "sao paulo",
      "são paulo"
    ]
  },
  "bogota": {
    "calendar": "chunky-dad-bogota",
    "timezone": "America/Bogota",
    "patterns": [
      "bogota",
      "bogotá"
    ]
  },
  "honolulu": {
    "calendar": "chunky-dad-honolulu",
    "timezone": "Pacific/Honolulu",
    "patterns": [
      "honolulu",
      "hawaii",
      "oahu",
      "waikiki"
    ]
  },
  "hong-kong": {
    "calendar": "chunky-dad-hongkong",
    "timezone": "Asia/Hong_Kong",
    "patterns": [
      "hong kong",
      "hk"
    ]
  },
  "tokyo": {
    "calendar": "chunky-dad-tokyo",
    "timezone": "Asia/Tokyo",
    "patterns": [
      "tokyo"
    ]
  }
};

// Export for different environments
// Scriptable environment
if (typeof module !== 'undefined' && module.exports) {
  module.exports = scraperCities;
}

// ES6 module environment
if (typeof window === 'undefined' && typeof importModule !== 'undefined') {
  // Scriptable environment - make available for importModule
  scraperCities;
} else if (typeof window !== 'undefined') {
  // Browser environment - attach to window
  window.scraperCities = scraperCities;
}

// Default export for ES6 modules
scraperCities;
