// Bear Event Scraper Bars Configuration
// This file is generated by tools/generate-scraper-bars.js from data/bars/*.json.
// Do not edit this file directly.
//
// USAGE RESTRICTIONS:
// - This is a pure JavaScript configuration file
// - Must export a default bars configuration object
// - Can be imported in both Scriptable and web environments
// - Keep this file environment-agnostic (no Scriptable or DOM APIs)
const scraperBars = {
  "bangkok": [
    {
      "name": "BEEF.BKK",
      "city": "bangkok",
      "address": "9th Fl. SilomEdge Si Lom Rd, Suriya Wong, Bang Rak, Bangkok 10500, Thailand",
      "coordinates": "13.729305880910303, 100.53569913387547",
      "instagram": "https://www.instagram.com/beef.bkk",
      "facebook": "https://www.facebook.com/beef.bkkbar/",
      "googleMaps": "https://maps.app.goo.gl/zEYjJa9v8AJJGUNB6"
    },
    {
      "name": "CAKE",
      "city": "bangkok",
      "address": "ตั้งอยู่ที่ 942/27 Rama IV Rd, Suriya Wong, Bang Rak, Bangkok 10500, Thailand",
      "coordinates": "13.730338066694463, 100.53405491726055",
      "instagram": "https://www.instagram.com/cake.bangkok",
      "facebook": "https://www.facebook.com/CakeBangkokTH/",
      "googleMaps": "https://maps.app.goo.gl/GrhBKQzDEFfvcUFn8"
    },
    {
      "name": "BARBER.BAR",
      "city": "bangkok",
      "address": "ชั้น 2 109/111 Si Lom Rd, Khwaeng Suriya Wong, Khet Bang Rak, Bangkok 10500, Thailand",
      "coordinates": "13.727938343038128, 100.53224466713601",
      "instagram": "https://www.instagram.com/bar.ber.bar/",
      "googleMaps": "https://maps.app.goo.gl/V96bZYM6qBm8tqQs5"
    }
  ],
  "boston": [
    {
      "name": "The Alley Bar",
      "city": "boston",
      "address": "14 Pi Alley, Boston, MA 02108",
      "coordinates": "42.358084, -71.0587317",
      "facebook": "https://www.facebook.com/thealleybarboston",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJDzxFQ4Rw44kRAxo45UBkJKM",
      "gayCities": "https://boston.gaycities.com/bars/127-the-alley-bar",
      "gayCitiesLastScrapedAt": "2026-06-13T20:34:56.886Z"
    }
  ],
  "chicago": [
    {
      "name": "Meeting House Tavern",
      "city": "chicago",
      "address": "5025 N Clark St, Chicago, IL 60640",
      "coordinates": "41.9732343, -87.6678243",
      "instagram": "https://www.instagram.com/meetinghousetavernchi",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJndazcVjTD4gRimEFGWVA_AU",
      "gayCities": "https://chicago.gaycities.com/bars/311263-meeting-house-tavern",
      "gayCitiesLastScrapedAt": "2026-06-13T18:37:35.740Z"
    },
    {
      "name": "The SoFo Tap",
      "city": "chicago",
      "address": "4923 N Clark St 1st floor, Chicago, IL 60640",
      "coordinates": "41.9724308, -87.6676099",
      "instagram": "https://www.instagram.com/thesofotap",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJUztUhCjSD4gRnZEajxMfo7Q",
      "gayCities": "https://chicago.gaycities.com/bars/2076-the-sofo-tap",
      "gayCitiesLastScrapedAt": "2026-06-13T18:37:37.979Z"
    },
    {
      "name": "Jackhammer",
      "city": "chicago",
      "address": "6406 N Clark St, Chicago, IL 60626",
      "coordinates": "41.9984139, -87.6710111",
      "instagram": "https://www.instagram.com/?hl=en",
      "facebook": "https://www.facebook.com/chijackhammer/",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ44RAWrzRD4gRDGoLchD_2SI",
      "gayCities": "https://chicago.gaycities.com/bars/176-jackhammer",
      "gayCitiesLastScrapedAt": "2026-06-13T18:37:40.195Z"
    },
    {
      "name": "Touché",
      "city": "chicago",
      "address": "6412 N Clark St, Chicago, IL 60626",
      "coordinates": "41.9985708, -87.670974",
      "instagram": "https://www.instagram.com/?hl=en",
      "facebook": "https://www.facebook.com/ToucheChicago",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJnwLkWrzRD4gREreJ-KlTEoU",
      "gayCities": "https://chicago.gaycities.com/bars/184-touch%C3%A9",
      "gayCitiesLastScrapedAt": "2026-06-13T20:34:54.431Z"
    },
    {
      "name": "Cell Block",
      "city": "chicago",
      "address": "3702 N Halsted St, Chicago, IL 60613",
      "coordinates": "41.9493268, -87.6498756",
      "instagram": "https://www.instagram.com/cellblockchi?fbclid=IwAR3LhbkA3SomCj4qvipwYyqsRpeFs6ANoAc4-LU8KvFOUKpRt_n2AyTHsqY",
      "facebook": "https://www.facebook.com/cellblockchi",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJP1xBx7DTD4gR1jLvMA_vZss",
      "gayCities": "https://chicago.gaycities.com/bars/145-cell-block",
      "gayCitiesLastScrapedAt": "2026-06-14T01:14:36.735Z"
    }
  ],
  "dallas": [
    {
      "name": "Station 4",
      "city": "dallas",
      "address": "3911 Cedar Springs Rd, Dallas, TX 75219",
      "coordinates": "32.810535, -96.8110709",
      "instagram": "https://www.instagram.com/s4dallas",
      "facebook": "https://www.facebook.com/S4Dallas",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJd6m0dcmeToYR3R7XzdFC07U",
      "gayCities": "https://dallas.gaycities.com/bars/213-station",
      "gayCitiesLastScrapedAt": "2026-06-26T15:16:43.357Z"
    }
  ],
  "fort-lauderdale": [
    {
      "name": "Eagle",
      "city": "fort-lauderdale",
      "address": "2209 Wilton Dr, Wilton Manors, FL 33305",
      "coordinates": "26.156486, -80.138547",
      "instagram": "https://www.instagram.com/eaglebarwm",
      "facebook": "https://www.facebook.com/EagleBarWM/",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJu6n6wQ0B2YgRuXxB9KC59OA",
      "gayCities": "https://fortlauderdale.gaycities.com/bars/309115-eagle-wilton-manors",
      "gayCitiesLastScrapedAt": "2026-06-13T22:28:52.503Z"
    },
    {
      "name": "Gym Sports Bar",
      "city": "fort-lauderdale",
      "address": "2287 Wilton Dr, Wilton Manors, FL 33305",
      "coordinates": "26.1572257, -80.1373084",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJPUAeAZwB2YgRL0hklcfzn6A",
      "gayCities": "https://fortlauderdale.gaycities.com/bars/309259-gym-sportsbar-wilton-manors",
      "gayCitiesLastScrapedAt": "2026-06-13T22:28:54.785Z"
    },
    {
      "name": "The Pub",
      "city": "fort-lauderdale",
      "address": "2283 Wilton Dr, Wilton Manors, FL 33305",
      "coordinates": "26.1571585, -80.1374938",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJj6QjAJwB2YgRf7XQXta65mY",
      "gayCities": "https://fortlauderdale.gaycities.com/bars/304345-the-pub-wilton-manors",
      "gayCitiesLastScrapedAt": "2026-06-14T03:19:23.849Z"
    },
    {
      "name": "Hunters",
      "city": "fort-lauderdale",
      "address": "2232-2238 Wilton Dr, Wilton Manors, FL 33305",
      "coordinates": "26.1557905, -80.1381831",
      "facebook": "https://www.facebook.com/huntersfl",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJde9xlp4B2YgRVl9hn3TriiI",
      "gayCities": "https://fortlauderdale.gaycities.com/bars/247-hunters-nightclub-wilton-manors",
      "gayCitiesLastScrapedAt": "2026-06-14T03:19:26.131Z"
    },
    {
      "name": "Scandals Saloon",
      "city": "fort-lauderdale",
      "address": "3073 NE 6th Ave, Wilton Manors, FL 33334",
      "coordinates": "26.1661037, -80.138715",
      "facebook": "https://www.facebook.com/scandalsfla",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJK4HWoYMB2YgRf442vxEUrM8",
      "gayCities": "https://fortlauderdale.gaycities.com/bars/256-scandals-saloon",
      "gayCitiesLastScrapedAt": "2026-06-14T03:19:30.718Z"
    }
  ],
  "hong-kong": [
    {
      "name": "Boo Bar",
      "city": "hong-kong",
      "address": "Hong Kong, Yau Ma Tei, Nathan Rd, 225號五樓 Pearl Oriental Tower",
      "coordinates": "22.304447393688015, 114.17136209855921",
      "instagram": "https://www.instagram.com/boobarhk",
      "facebook": "https://www.facebook.com/boobar.hk/",
      "googleMaps": "https://maps.app.goo.gl/jPTA9KhoNaEzNhCJA"
    }
  ],
  "honolulu": [
    {
      "name": "Hula's Bar and Lei Stand",
      "city": "honolulu",
      "address": "134 Kapahulu Ave, Honolulu, HI 96815",
      "coordinates": "21.2718488, -157.8216485",
      "instagram": "https://www.instagram.com/hulaswaikiki",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ58CUmHByAHwRx45RwUAMUzo",
      "gayCities": "https://hawaii.gaycities.com/bars/276-hulas-bar-lei-stand",
      "gayCitiesLastScrapedAt": "2026-06-14T07:46:30.629Z"
    },
    {
      "name": "In Between",
      "city": "honolulu",
      "address": "2155 Lauula St, Honolulu, HI 96815",
      "coordinates": "21.2807141, -157.8297099",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJK93OZIptAHwRwR-r34F8Zj4",
      "gayCities": "https://hawaii.gaycities.com/bars/277-in-between",
      "gayCitiesLastScrapedAt": "2026-06-14T07:46:32.659Z"
    }
  ],
  "la": [
    {
      "name": "Eagle LA",
      "city": "la",
      "address": "4219 Santa Monica Blvd, Los Angeles, CA 90029",
      "coordinates": "34.0912127, -118.2840632",
      "instagram": "dirtybird_la",
      "facebook": "https://www.facebook.com/eagle.bar.la/",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJLwuhHU_HwoARdQQ1PfOn6B4",
      "gayCities": "https://losangeles.gaycities.com/bars/357-eagle-la",
      "gayCitiesLastScrapedAt": "2026-06-13T15:14:53.360Z"
    },
    {
      "name": "Precinct LA",
      "city": "la",
      "address": "357 S Broadway, Los Angeles, CA 90013",
      "coordinates": "34.0498149, -118.2493321",
      "instagram": "https://www.instagram.com/precinctdtla",
      "facebook": "https://www.facebook.com/precinctdtla",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ16rgokvGwoARgLmCBWa28wI",
      "gayCities": "https://losangeles.gaycities.com/bars/306866-precinct",
      "gayCitiesLastScrapedAt": "2026-06-13T15:14:55.610Z"
    },
    {
      "name": "Akbar",
      "city": "la",
      "address": "4356 Sunset Blvd, Los Angeles, CA 90029",
      "coordinates": "34.0956924, -118.2842979",
      "facebook": "https://www.facebook.com/Akbarsilverlake",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJOwpNUEzHwoARAPHUIkcyjdM",
      "gayCities": "https://losangeles.gaycities.com/bars/359-akbar",
      "gayCitiesLastScrapedAt": "2026-06-13T18:37:31.295Z"
    },
    {
      "name": "The Falcon",
      "city": "la",
      "address": "1435 E Broadway, Long Beach, CA 90802",
      "coordinates": "33.768209, -118.173899",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJqVioYxAx3YARhUlzgOXT0Zs",
      "gayCities": "https://longbeach.gaycities.com/bars/1215-falcon",
      "gayCitiesLastScrapedAt": "2026-06-13T18:37:33.538Z"
    },
    {
      "name": "GYM Bar",
      "city": "la",
      "address": "8919 Santa Monica Blvd, West Hollywood, CA 90069",
      "coordinates": "34.0847604, -118.3846815",
      "instagram": "https://www.instagram.com/wehogymbar",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJXxXPUMi_woARE46Y7WO-Ww0",
      "gayCities": "https://losangeles.gaycities.com/bars/309258-gym-bar-weho",
      "gayCitiesLastScrapedAt": "2026-06-14T03:19:33.089Z"
    }
  ],
  "london": [
    {
      "name": "Royal Vauxhall Tavern",
      "city": "london",
      "address": "372 Kennington Ln, London, United Kingdom SE11 5HY",
      "coordinates": "51.4863391, -0.1217784",
      "instagram": "https://www.instagram.com/rvtofficial",
      "facebook": "https://www.facebook.com/TheRVT",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJuYgA--wEdkgRD-0ylWTyMkw",
      "gayCities": "https://london.gaycities.com/bars/1710-royal-vauxhall-tavern",
      "gayCitiesLastScrapedAt": "2026-06-13T15:19:24.741Z"
    },
    {
      "name": "Duke of Wellington",
      "city": "london",
      "address": "77 Wardour St, London, England W1D 6QA",
      "coordinates": "51.512343, -0.1331208",
      "instagram": "https://www.instagram.com/dukeofwellington_soho",
      "facebook": "https://www.facebook.com/Duke.Of.Welly",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJkUcf6v4PdkgR8zHSLztcmdw",
      "gayCities": "https://london.gaycities.com/bars/1704-the-duke-of-wellington",
      "gayCitiesLastScrapedAt": "2026-06-13T16:37:27.264Z"
    },
    {
      "name": "Kings Arms",
      "city": "london",
      "address": "23 Poland St, London, England W1F 8QL",
      "coordinates": "51.5151643, -0.1371827",
      "instagram": "https://www.instagram.com/KingsArms.soho",
      "facebook": "https://www.facebook.com/kingsarms.soho",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJBUDtIZcEdkgR0k-Xw7rA8wM",
      "gayCities": "https://london.gaycities.com/bars/2046-the-kings-arms",
      "gayCitiesLastScrapedAt": "2026-06-13T16:37:29.296Z"
    },
    {
      "name": "Eagle London",
      "city": "london",
      "address": "349 Kennington Lane, London, England SE11 5QY",
      "coordinates": "51.4862598, -0.1193404",
      "instagram": "https://www.instagram.com/eagleldn",
      "facebook": "https://www.facebook.com/EagleLDN",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ-crt4uwEdkgRt13r0ih1Lgk",
      "gayCities": "https://london.gaycities.com/bars/1685-eagle-london",
      "gayCitiesLastScrapedAt": "2026-06-13T16:37:31.585Z"
    }
  ],
  "montreal": [
    {
      "name": "Le Stud",
      "city": "montreal",
      "address": "1812 Rue Sainte-Catherine E, Montreal, QC H2K 2H3",
      "coordinates": "45.522756, -73.5519804",
      "facebook": "https://www.facebook.com/groups/42513323876/",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ6615i68byUwRS5KOpOHOFB8",
      "gayCities": "https://montreal.gaycities.com/bars/724-le-stud",
      "gayCitiesLastScrapedAt": "2026-06-14T01:14:32.066Z"
    },
    {
      "name": "Aigle Noir",
      "city": "montreal",
      "address": "1315 St Catherine St E, Montreal, QC H2L 2H4",
      "coordinates": "45.519641, -73.555339",
      "facebook": "https://www.facebook.com/Bar.Aigle.Noir/",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJEc7NGK4byUwR1QVPh5qsYCY",
      "gayCities": "https://montreal.gaycities.com/bars/710-aigle-noir",
      "gayCitiesLastScrapedAt": "2026-06-14T01:14:34.423Z"
    }
  ],
  "nyc": [
    {
      "name": "Animal",
      "city": "nyc",
      "address": "307 Meeker Ave, NY 11211",
      "coordinates": "40.7173904, -73.9493112",
      "instagram": "https://www.instagram.com/animal.nyc",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJdaGX6E9ZwokRrcrhq8cMM-8",
      "gayCities": "https://newyork.gaycities.com/bars/312406-animal",
      "gayCitiesLastScrapedAt": "2026-06-14T16:38:14.085Z"
    },
    {
      "name": "Rockbar",
      "city": "nyc",
      "address": "185 Christopher St, New York, NY 10014",
      "coordinates": "40.7326534, -74.0096996",
      "instagram": "https://www.instagram.com/rockbarnyc",
      "facebook": "https://www.facebook.com/Rockbar-NYC",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJlwfqXuxZwokRTlizRW_4cwc",
      "gayCities": "https://newyork.gaycities.com/bars/3486-rockbar-nyc",
      "gayCitiesLastScrapedAt": "2026-06-14T16:38:16.402Z"
    },
    {
      "name": "Eagle NYC",
      "city": "nyc",
      "address": "554 W 28th St, New York, NY 10001",
      "coordinates": "40.751694, -74.004306",
      "website": "http://eagle-ny.com",
      "instagram": "https://www.instagram.com/eaglenyc",
      "facebook": "https://www.facebook.com/eaglenyc",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJmaM5RbZZwokRwpJUp-ClLKw",
      "wikipedia": "https://en.wikipedia.org/wiki/Eagle_NYC",
      "gayCities": "https://newyork.gaycities.com/bars/400-eagle-nyc",
      "faviconBg": "#f0f0f0",
      "faviconFg": "#565656",
      "gayCitiesLastScrapedAt": "2026-06-26T17:08:38.515Z",
      "wikipediaLastScrapedAt": "2026-06-26T15:16:42.784Z"
    },
    {
      "name": "3 Dollar Bill",
      "city": "nyc",
      "address": "260 Meserole St, Brooklyn, NY 11206",
      "coordinates": "40.7084144, -73.9380583",
      "instagram": "https://www.instagram.com/3dollarbillbk",
      "facebook": "https://www.facebook.com/3dollarbillbk",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ7zm6H3JbwokR3ui1wTNr6Xc",
      "gayCities": "https://newyork.gaycities.com/bars/309059-dollar-bill",
      "gayCitiesLastScrapedAt": "2026-06-14T16:38:18.601Z"
    },
    {
      "name": "Ty's",
      "city": "nyc",
      "address": "114 Christopher St, New York, NY 10014",
      "coordinates": "40.7330387, -74.0052985",
      "instagram": "https://www.instagram.com/tysbar",
      "facebook": "https://www.facebook.com/TysNYC",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJaVvpXJNZwokRT3p02KL_TrY",
      "gayCities": "https://newyork.gaycities.com/bars/388-tys-bar-nyc",
      "gayCitiesLastScrapedAt": "2026-06-14T16:38:20.711Z"
    },
    {
      "name": "Nowhere Bar",
      "city": "nyc",
      "address": "322 E 14th St, New York, NY 10003",
      "coordinates": "40.7316977, -73.9841737",
      "instagram": "https://www.instagram.com/nowherenyc",
      "facebook": "https://www.facebook.com/nowherebar",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJZ1fMFZ5ZwokRkYrV85CZorY",
      "gayCities": "https://newyork.gaycities.com/bars/415-nowhere-bar",
      "gayCitiesLastScrapedAt": "2026-06-14T16:38:22.742Z"
    },
    {
      "name": "Albatross",
      "city": "nyc",
      "address": "3619 24th Ave, Queens, NY 11103",
      "coordinates": "40.7701915, -73.9121803",
      "facebook": "https://www.facebook.com/albatrossastoria",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ8RSx_WlfwokRa_PTy_InEnM",
      "gayCities": "https://newyork.gaycities.com/bars/449-albatross-bar",
      "gayCitiesLastScrapedAt": "2026-06-13T15:19:27.078Z"
    },
    {
      "name": "Gym Sports Bar",
      "city": "nyc",
      "address": "167 8th Ave, New York, NY 10011",
      "coordinates": "40.7426478, -74.0007982",
      "instagram": "https://www.instagram.com/gymsportsbarny",
      "facebook": "https://www.facebook.com/GYMSPORTSBARNY",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJX-P_qr5ZwokR7pssvk2V9b0",
      "gayCities": "https://newyork.gaycities.com/bars/394-gym-sportsbar",
      "gayCitiesLastScrapedAt": "2026-06-13T22:28:57.028Z"
    },
    {
      "name": "FLEX",
      "city": "nyc",
      "address": "405 W 51st St, New York, NY 10019",
      "coordinates": "40.7644457, -73.9888453",
      "instagram": "https://www.instagram.com/flexnyc",
      "facebook": "https://www.facebook.com/flexbarnyc",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJBWXY9oZZwokRA9xrSOqTNjc",
      "gayCities": "https://newyork.gaycities.com/bars/311127-flex",
      "gayCitiesLastScrapedAt": "2026-06-14T07:46:24.312Z"
    },
    {
      "name": "Atlas Social Club",
      "city": "nyc",
      "address": "753 9th Ave, New York, NY 10019",
      "coordinates": "40.7640829, -73.9889102",
      "facebook": "https://www.facebook.com/atlassocialclub",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJSYrBMldYwokRuer87cJcwiw",
      "gayCities": "https://newyork.gaycities.com/bars/305118-atlas-social-club",
      "gayCitiesLastScrapedAt": "2026-06-14T07:46:26.352Z"
    },
    {
      "name": "9th Avenue Saloon",
      "city": "nyc",
      "address": "656 9th Ave, New York, NY 10036",
      "coordinates": "40.7607576, -73.9906454",
      "instagram": "https://www.instagram.com/9thavesaloon",
      "facebook": "https://www.facebook.com/9thAveSaloon",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJte-0gz9ZwokR5wz0wDUVOpQ",
      "gayCities": "https://newyork.gaycities.com/bars/426-th-avenue-saloon",
      "gayCitiesLastScrapedAt": "2026-06-14T07:46:28.587Z"
    }
  ],
  "palm-springs": [
    {
      "name": "Hunters",
      "city": "palm-springs",
      "address": "302 E Arenas Rd, Palm Springs, CA 92262",
      "coordinates": "33.8214288, -116.544092",
      "instagram": "https://www.instagram.com/hunterspalmsprings",
      "facebook": "https://www.facebook.com/HuntersPS",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJbXdJHxEb24ARI5sarz94EAI",
      "gayCities": "https://palmsprings.gaycities.com/bars/588-hunters-palm-springs",
      "gayCitiesLastScrapedAt": "2026-06-14T03:19:28.458Z"
    }
  ],
  "paris": [
    {
      "name": "Bear's Den",
      "city": "paris",
      "address": "6 Rue des Lombards, Paris, IDF 75004",
      "coordinates": "48.8591657, 2.3500783",
      "facebook": "https://www.facebook.com/Bearsden-Paris-306571042732756/",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ3wmsgx5u5kcRX4l_NuRC3z0",
      "gayCities": "https://paris.gaycities.com/bars/1625-bears-den",
      "gayCitiesLastScrapedAt": "2026-06-13T16:37:22.662Z"
    },
    {
      "name": "El Hombre",
      "city": "paris",
      "address": "15 rue de la Reynie, Paris, France 75004",
      "coordinates": "48.859861, 2.349458",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJsYcLoB5u5kcRvlZDfSyg7w4",
      "gayCities": "https://paris.gaycities.com/bars/307921-el-hombre",
      "gayCitiesLastScrapedAt": "2026-06-13T16:37:24.689Z"
    }
  ],
  "poconos": [
    {
      "name": "Camp Out",
      "city": "poconos",
      "address": "446 MT NEBO RD, EAST STROUDSBURG, PA, 18301",
      "coordinates": "41.0219799, -75.1167816",
      "website": "https://campoutpoconos.com",
      "instagram": "https://www.instagram.com/campoutpoconos",
      "facebook": "https://www.facebook.com/campout.poconos",
      "googleMaps": "https://maps.app.goo.gl/LYwCKGeMJAJTy8hx9?g_st=ic",
      "faviconBg": "#f4f3ef",
      "faviconFg": "#60514d"
    }
  ],
  "portland": [
    {
      "name": "CC Slaughters",
      "city": "portland",
      "address": "219 NW Davis St, Portland, OR 97209",
      "coordinates": "45.5246478, -122.6729183",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJnfNLuwAKlVQRXZrfhfLp_i4",
      "gayCities": "https://portland.gaycities.com/bars/893-cc-slaughters-nightclub-and-lounge",
      "gayCitiesLastScrapedAt": "2026-06-13T22:29:01.943Z"
    }
  ],
  "ptown": [
    {
      "name": "A-House",
      "city": "ptown",
      "address": "6 Masonic Pl #4, Provincetown, MA 02657",
      "coordinates": "42.0500638, -70.1888875",
      "facebook": "https://www.facebook.com/ahouseprovincetown",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJyQ3ZXX6n_IkR0_ZfyWwD6Zg",
      "gayCities": "https://ptown.gaycities.com/bars/535-a-house",
      "gayCitiesLastScrapedAt": "2026-06-13T20:34:59.308Z"
    },
    {
      "name": "Boatslip",
      "city": "ptown",
      "address": "161 Commercial St, Provincetown, MA 02657",
      "coordinates": "42.0470329, -70.1901852",
      "instagram": "https://www.instagram.com/boatslipresort",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ-fvjNIBY-4kRHNO3kg_G5Cc",
      "gayCities": "https://ptown.gaycities.com/hotels/10272-boatslip-resort-beach-club",
      "gayCitiesLastScrapedAt": "2026-06-13T20:35:01.413Z"
    },
    {
      "name": "Crown & Anchor",
      "city": "ptown",
      "address": "247 Commercial St, Provincetown, MA 02657",
      "coordinates": "42.0502291, -70.1876737",
      "facebook": "https://www.facebook.com/CrownAnchorProvincetown",
      "googleMaps": "https://www.google.com/maps/place/?q=247+Commercial+St,+Provincetown,+MA+02657",
      "gayCities": "https://ptown.gaycities.com/bars/541-crown-anchor",
      "gayCitiesLastScrapedAt": "2026-06-13T20:35:03.709Z"
    },
    {
      "name": "Purgatory Gifford House",
      "city": "ptown",
      "address": "11 Carver St, Provincetown, MA 02657",
      "coordinates": "42.0496268, -70.1900224",
      "instagram": "https://www.instagram.com/gifford_house",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJE9zxSn6n_IkRbOMJFiVbw_k",
      "gayCities": "https://ptown.gaycities.com/bars/543-purgatory-gifford-house",
      "gayCitiesLastScrapedAt": "2026-06-14T01:14:29.670Z"
    },
    {
      "name": "Red Room",
      "city": "ptown",
      "address": "258 Commercial St, Provincetown, MA 02657",
      "coordinates": "42.0510476, -70.1876737",
      "instagram": "https://www.instagram.com/redroomptown",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJqbgqyVOn_IkRIAI-jRz2eak",
      "gayCities": "https://ptown.gaycities.com/bars/309562-red-room",
      "gayCitiesLastScrapedAt": "2026-06-26T15:16:45.767Z"
    }
  ],
  "pv": [
    {
      "name": "STUDS",
      "city": "pv",
      "address": "283 Basilio Badillo, Puerto Vallarta, Jal. 48380",
      "coordinates": "20.6025646, -105.2351825",
      "facebook": "https://www.facebook.com/studsbarpv/",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJYT0eSbpFIYQRxx74YO-xYsY",
      "gayCities": "https://vallarta.gaycities.com/bars/309956-studs-bear-bar",
      "gayCitiesLastScrapedAt": "2026-06-13T15:19:29.495Z"
    },
    {
      "name": "CC Slaughters",
      "city": "pv",
      "address": "Lazaro Cardenas 254, Puerto Vallarta, JAL 48290",
      "coordinates": "20.6483408, -105.1980403",
      "facebook": "https://www.facebook.com/CCSlaughtersPV/",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJZa2WW0xFIYQRrzpGYnmf8Og",
      "gayCities": "https://vallarta.gaycities.com/bars/302724-cc-slaughters",
      "gayCitiesLastScrapedAt": "2026-06-13T22:28:59.439Z"
    }
  ],
  "seattle": [
    {
      "name": "Diesel",
      "city": "seattle",
      "address": "1413 14th Ave, Seattle, WA 98122",
      "coordinates": "47.6133, -122.3143",
      "website": "http://dieselseattle.com/DIESEL.html",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJCfyfcs5qkFQR84fyFrPsC58",
      "wikipedia": "https://en.wikipedia.org/wiki/Diesel_(gay_bar)",
      "gayCities": "https://seattle.gaycities.com/bars/302690-diesel",
      "faviconBg": "#335a91",
      "faviconFg": "#c3cbd4",
      "gayCitiesLastScrapedAt": "2026-06-26T17:08:40.863Z",
      "wikipediaLastScrapedAt": "2026-06-26T15:16:42.812Z"
    },
    {
      "name": "The Lumber Yard Bar",
      "city": "seattle",
      "address": "9630 16th Ave SW, Seattle, WA 98106",
      "coordinates": "47.5165235, -122.3548059",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ-8uYrt9DkFQRXv1WZmNZ8F0",
      "gayCities": "https://seattle.gaycities.com/bars/309627-the-lumber-yard-bar",
      "gayCitiesLastScrapedAt": "2026-06-13T15:14:46.563Z"
    },
    {
      "name": "The Cuff Complex",
      "city": "seattle",
      "address": "1533 13th Ave, Seattle, WA 98122",
      "coordinates": "47.6150778, -122.3157208",
      "facebook": "https://www.facebook.com/thecuffcomplex",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJuQVbk81qkFQRkm6N_RnwHQY",
      "gayCities": "https://seattle.gaycities.com/bars/514-the-cuff-complex",
      "gayCitiesLastScrapedAt": "2026-06-13T15:14:48.626Z"
    },
    {
      "name": "Seattle Eagle",
      "city": "seattle",
      "address": "314 E Pike St, Seattle, WA 98122",
      "coordinates": "47.61427, -122.32708",
      "website": "http://seattleeagle.com",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJOcPt38pqkFQRWmTOs3bUrgk",
      "wikipedia": "https://en.wikipedia.org/wiki/Seattle_Eagle",
      "gayCities": "https://seattle.gaycities.com/bars/506-seattle-eagle",
      "gayCitiesLastScrapedAt": "2026-06-26T17:08:43.316Z",
      "wikipediaLastScrapedAt": "2026-06-26T15:16:42.842Z"
    },
    {
      "name": "CC’s Seattle",
      "city": "seattle",
      "address": "1701 E Olive Wy, Seattle, WA 98102",
      "coordinates": "47.6196626, -122.3233158",
      "facebook": "https://www.facebook.com/ccsseattle",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJk-Ws_tFqkFQRc2h8MPRvv5I",
      "gayCities": "https://seattle.gaycities.com/bars/505-ccs-seattle",
      "gayCitiesLastScrapedAt": "2026-06-13T15:14:51.206Z"
    },
    {
      "name": "Madison Pub",
      "city": "seattle",
      "address": "1315 E Madison St, Seattle, WA 98122",
      "coordinates": "47.6133619, -122.3149054",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJB_-ecc5qkFQRS1xH4lgadrg",
      "gayCities": "https://seattle.gaycities.com/bars/508-madison-pub",
      "gayCitiesLastScrapedAt": "2026-06-13T15:19:20.182Z"
    },
    {
      "name": "Pony",
      "city": "seattle",
      "address": "1221 E Madison St, Seattle, WA 98122",
      "coordinates": "47.6130663, -122.3157243",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJRUOyfc5qkFQRDZLLFj1Q264",
      "gayCities": "https://seattle.gaycities.com/bars/2442-pony",
      "gayCitiesLastScrapedAt": "2026-06-13T15:19:22.288Z"
    }
  ],
  "sf": [
    {
      "name": "SF Eagle",
      "city": "sf",
      "address": "398 12th St, San Francisco, CA 94103",
      "coordinates": "37.7699927, -122.4134077",
      "instagram": "https://www.instagram.com/sfeaglebar",
      "facebook": "https://www.facebook.com/SFEagleBar",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJeQ6_GyZ-j4ARj3aV_MeMyf8",
      "gayCities": "https://sanfrancisco.gaycities.com/bars/304619-sf-eagle",
      "gayCitiesLastScrapedAt": "2026-06-14T05:42:19.861Z"
    },
    {
      "name": "Powerhouse",
      "city": "sf",
      "address": "1347 Folsom St, San Francisco, CA 94103",
      "coordinates": "37.773088, -122.412193",
      "instagram": "https://www.instagram.com/sfpowerhouse",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJY_ioDSh-j4ARCCFmqIVhgZo",
      "gayCities": "https://sanfrancisco.gaycities.com/bars/43-powerhouse",
      "gayCitiesLastScrapedAt": "2026-06-14T05:42:22.526Z"
    },
    {
      "name": "Hole in the Wall Saloon",
      "city": "sf",
      "address": "1369 Folsom St, San Francisco, CA 94103",
      "coordinates": "37.7729155, -122.4123163",
      "instagram": "https://www.instagram.com/the-hole-in-the-wall-saloon",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJExXNdCh-j4AR6JuGm4ElqcQ",
      "gayCities": "https://sanfrancisco.gaycities.com/bars/40-hole-in-the-wall-saloon",
      "gayCitiesLastScrapedAt": "2026-06-14T05:42:24.790Z"
    },
    {
      "name": "Lone Star Saloon",
      "city": "sf",
      "address": "1354 Harrison St, San Francisco, CA 94103",
      "coordinates": "37.7721717, -122.410901",
      "facebook": "https://www.facebook.com/lonestarsf",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJ4yvd8Ch-j4ARGZFAn1jfTl8",
      "gayCities": "https://sanfrancisco.gaycities.com/bars/42-lone-star-saloon",
      "gayCitiesLastScrapedAt": "2026-06-14T05:42:27.073Z"
    },
    {
      "name": "440 Castro",
      "city": "sf",
      "address": "440 Castro St, San Francisco, CA 94114",
      "coordinates": "37.7618335, -122.4352736",
      "instagram": "https://www.instagram.com/440castro",
      "facebook": "https://www.facebook.com/440Castro",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJlYxnqhx-j4ARE6-6BQBetEI",
      "gayCities": "https://sanfrancisco.gaycities.com/bars/3-castro",
      "gayCitiesLastScrapedAt": "2026-06-14T05:42:29.719Z"
    }
  ],
  "tokyo": [
    {
      "name": "EAGLE TOKYO",
      "city": "tokyo",
      "address": "2 Chome-12-3 Shinjuku, Tokyo, Tōkyō-to 160-0022",
      "coordinates": "35.6904391, 139.7076017",
      "facebook": "https://www.facebook.com/eagletokyojp",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJAQCrt9yMGGARObx5wDPQtAA",
      "gayCities": "https://tokyo.gaycities.com/bars/307927-eagle-tokyo",
      "gayCitiesLastScrapedAt": "2026-06-14T09:13:52.895Z"
    },
    {
      "name": "EAGLE TOKYO BLUE",
      "city": "tokyo",
      "address": "2 Chome−11−2 Casa Verde, 1階、地下1階, Shinjuku City, Tokyo 160-0022",
      "coordinates": "35.690086, 139.7077713",
      "instagram": "https://www.instagram.com/eagletokyojp",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJVVvvklSNGGAR4pCosef9zpQ",
      "gayCities": "https://tokyo.gaycities.com/bars/312380-eagle-tokyo-blue",
      "gayCitiesLastScrapedAt": "2026-06-14T09:13:55.162Z"
    }
  ],
  "vegas": [
    {
      "name": "Fun Hog Ranch",
      "city": "vegas",
      "address": "495 E Twain Ave, Las Vegas, NV 89169",
      "coordinates": "36.1208359, -115.1522707",
      "instagram": "https://www.instagram.com/funhogranchlv",
      "googleMaps": "https://www.google.com/maps/place/?q=place_id:ChIJKfM4OVvEyIARKXe7Mp57Uv0",
      "gayCities": "https://lasvegas.gaycities.com/bars/1346-fun-hog-ranch",
      "gayCitiesLastScrapedAt": "2026-06-14T01:14:27.328Z"
    }
  ]
};

// Export for different environments
// Scriptable environment
if (typeof module !== 'undefined' && module.exports) {
  module.exports = scraperBars;
}

// ES6 module environment
if (typeof window === 'undefined' && typeof importModule !== 'undefined') {
  // Scriptable environment - make available for importModule
  scraperBars;
} else if (typeof window !== 'undefined') {
  // Browser environment - attach to window
  window.scraperBars = scraperBars;
}

// Default export for ES6 modules
scraperBars;
