name: Bars Data Sync

on:
  schedule:
    # Run every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-bars:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Sync bars data
      env:
        GOOGLE_APP_SCRIPT_URL: ${{ secrets.GOOGLE_APP_SCRIPT_URL }}
        GOOGLE_APP_SCRIPT_KEY: ${{ secrets.GOOGLE_APP_SCRIPT_KEY }}
      run: node scripts/sync-bars.js
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/bars/
        git diff --staged --quiet || git commit -m "Auto-sync bars data from Google Sheets"
        git push
