name: Update Testing Manifest

on:
  push:
    paths:
      - 'testing/*.html'
  pull_request:
    paths:
      - 'testing/*.html'

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Generate manifest
      run: |
        cd testing
        node generate-manifest.js
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add testing/manifest.json
        git diff --staged --quiet || git commit -m "Update testing manifest"
    
    - name: Push changes
      if: github.event_name == 'push'
      run: git push